#ifndef KANJIPAD_DATASTRUCTURE_DEFINITIONS_HEADER
#define KANJIPAD_DATASTRUCTURE_DEFINITIONS_HEADER

typedef struct {
  gchar d[2];
} kp_wchar;

#endif /* KANJIPAD_DATASTRUCTURE_DEFINITIONS_HEADER */
